theme: jekyll-theme-minimal
title: Ariel Chen Realty
description: Your Trusted Local Realtor in Bay Area. <br> Brings Value to Your Community!
logo: /assets/img/photo-logo.png
show_downloads: false
google_analytics: UA-137015374-1
