theme: jekyll-theme-minimal
title: Ariel Chen Realty
description: Your Trusted Local Realtor in Bay Area. <br> Brings Value to Your Community! <br> Proficient in both English and Mandarin.
logo: /assets/img/public/photo-logo.png
show_downloads: false
google_analytics: UA-137015374-1
